version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build \
              -t rsdatatechnologies/k8s-cli-toolset:latest .
      - deploy:
          name: Push Docker image
          command: |
            docker login -u $DOCKERCLOUD_USER -p $DOCKERCLOUD_PASS
            docker tag rsdatatechnologies/k8s-cli-toolset:latest rsdatatechnologies/k8s-cli-toolset:$CIRCLE_SHA1
            docker push rsdatatechnologies/k8s-cli-toolset:latest
            docker push rsdatatechnologies/k8s-cli-toolset:$CIRCLE_SHA1

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master